"""add leakfix_info table

Revision ID: 276545452e63
Revises: f261f76e8c3d
Create Date: 2024-01-23 16:45:00.558269

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '276545452e63'
down_revision = 'f261f76e8c3d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leakfix_info',
    sa.Column('url', sa.String(length=255), nullable=False, comment='漏洞病毒库url'),
    sa.Column('name', sa.String(length=64), nullable=True, comment='项目名称'),
    sa.Column('addr', sa.String(length=255), nullable=False, comment='文件下载路径'),
    sa.Column('size', sa.Integer(), nullable=True, comment='文件大小'),
    sa.Column('md5', sa.String(length=64), nullable=False, comment='文件MD5'),
    sa.Column('c_time', sa.DateTime(), nullable=False, comment='病毒漏洞库创建时间'),
    sa.Column('remark', sa.String(length=128), nullable=True, comment='备注'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('creation_date', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人ID'),
    sa.Column('updation_date', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='更新人ID'),
    sa.Column('enabled_flag', sa.Boolean(), nullable=False, comment='是否删除, 0 删除 1 非删除'),
    sa.Column('trace_id', sa.String(length=255), nullable=True, comment='trace_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8'
    )

    # ### end Alembic commands ###
