"""init

Revision ID: 6bd7291858d4
Revises: d57d084ba0bf
Create Date: 2023-07-24 16:15:58.315102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bd7291858d4'
down_revision = 'd57d084ba0bf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
