"""module update

Revision ID: ab4d63e310aa
Revises: 6bd7291858d4
Create Date: 2023-08-03 18:23:25.816077

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ab4d63e310aa'
down_revision = '6bd7291858d4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('module_info', 'remarks',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=255),
               nullable=True,
               existing_comment='其他信息')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('module_info', 'remarks',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=255),
               nullable=False,
               existing_comment='其他信息')
    # ### end Alembic commands ###
