"""module update 1

Revision ID: e9eadc35e0d1
Revises: ab4d63e310aa
Create Date: 2023-08-04 10:40:56.307626

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e9eadc35e0d1'
down_revision = 'ab4d63e310aa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('module_info', 'simple_desc',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=255),
               nullable=True,
               existing_comment='简要描述')
    op.alter_column('module_info', 'module_packages',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=255),
               nullable=True,
               existing_comment='模块对应的包名称')
    op.alter_column('module_info', 'priority',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=255),
               nullable=True,
               existing_comment='默认执行用例优先级')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('module_info', 'priority',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=255),
               nullable=False,
               existing_comment='默认执行用例优先级')
    op.alter_column('module_info', 'module_packages',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=255),
               nullable=False,
               existing_comment='模块对应的包名称')
    op.alter_column('module_info', 'simple_desc',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=255),
               nullable=False,
               existing_comment='简要描述')
    # ### end Alembic commands ###
